directories = [
  "~/dev",
  "~/dev/sykes",
  "~/dev/msp",
  "~/dev/cdk",
  "~/dev/native",
  "~/dev/guide",
  "~/dev/report",
  "~/personal",
  "~/.dotfiles",
  "~/.dotfiles/.config",
  "~/projects",
  "~/projects/sykes",
  "~/projects/msp",
  "~/projects/cdk",
  "~/projects/native",
  "~/projects/digital-guide",
  "~/projects/reports",
  "~/github",
  "~/plugins"
]
max_depth = 1
display_tilde = true
exclude_current_session = true
navigate_session = true
